rails_root = Pathname.new(File.dirname(__FILE__)).join("..")

Gem.sources.each { |uri| source uri }

gem "activesupport", "3.0.pre", :vendored_at => rails_root.join("activesupport")
gem "arel", :git => "git://github.com/rails/arel.git"

only :test do
  gem "sqlite3-ruby"
end

disable_system_gems
