# frozen_string_literal: true

require "rake/testtask"

task default: :test

task :package

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList["#{__dir__}/test/cases/**/*_test.rb"]
  t.warning = true
  t.verbose = true
  t.ruby_opts = ["--dev"] if defined?(JRUBY_VERSION)
end

namespace :test do
  task :isolated do
    Dir.glob("#{__dir__}/test/**/*_test.rb").all? do |file|
      sh(Gem.ruby, "-w", "-I#{__dir__}/lib", "-I#{__dir__}/test", file)
    end || raise("Failures")
  end
end
