require 'action_view/vendor/html-scanner'

module ActionDispatch
  module Assertions
    module DomAssertions
      # \Test two HTML strings for equivalency (e.g., identical up to reordering of attributes)
      #
      #   # assert that the referenced method generates the appropriate HTML string
      #   assert_dom_equal '<a href="http://www.example.com">Apples</a>', link_to("Apples", "http://www.example.com")
      def assert_dom_equal(expected, actual, message = "", require_closing_tag = true)
        expected_dom = HTML::Document.new(expected).root
        actual_doc   = HTML::Document.new(actual)
        actual_dom   = actual_doc.root
        assert_equal expected_dom, actual_dom
        assert !actual_doc.inferred_closing_tag, "Although the DOM's match, the markup generated by Rails was missing a closing tag and may not be rendered correctly in a browser.  Markup: #{actual}" if require_closing_tag
      end

      # The negated form of +assert_dom_equivalent+.
      #
      #   # assert that the referenced method does not generate the specified HTML string
      #   assert_dom_not_equal '<a href="http://www.example.com">Apples</a>', link_to("Oranges", "http://www.example.com")
      def assert_dom_not_equal(expected, actual, message = "")
        expected_dom = HTML::Document.new(expected).root
        actual_dom   = HTML::Document.new(actual).root
        refute_equal expected_dom, actual_dom
      end
    end
  end
end
