lib_dir = Pathname.new(File.dirname(__FILE__)).join('lib')
vendor_dir = lib_dir.join('active_support', 'vendor')

# gem 'builder', '~> 2.1.2'
# gem 'memcache-client', '>= 1.6.5'
# gem 'tzinfo', '~> 0.3.13'
# gem 'i18n', '~> 0.1.3'

gem 'builder', '2.1.2', :vendored_at => vendor_dir.join('builder-2.1.2')
gem 'memcache-client', '1.6.5', :vendored_at => vendor_dir.join('memcache-client-1.6.5')
gem 'tzinfo', '0.3.13', :vendored_at => vendor_dir.join('tzinfo-0.3.13')
gem 'i18n', '0.1.3', :vendored_at => vendor_dir.join('i18n-0.1.3')

only :test do
  gem 'mocha', '>= 0.9.7'
end

disable_rubygems
