# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"


gem "minitest", "~>5.1", :group => [:development, :test]
gem "rdoc", "~>4.0", :group => [:development, :test]
gem "hoe", "~>3.5", :group => [:development, :test]

# vim: syntax=ruby
