# frozen_string_literal: true

# This task enhances our travis yaml with two new features:
#
# 1) arbitrary keys associated with a single 'env' value in the matrix
#    (used to apply addons only to the env that needs them, for example)
#
# 2) 'addition' keys in the matrix: a key named `foo+` will have its
#    value added to the root value for `foo`. This allows us to specify
#    an extra before_install step without repeating the common part.
#
task :travis do
  require "yaml"

  y = YAML.load_file(".travis.source.yml")
  custom_matrix = y.delete("rvm_matrix")
  ruby_versions = y.delete("rvm")
  primary_inclusions = []

  expand_additions = lambda do |entry|
    entry.keys.grep(/\+$/).each do |addition_key|
      base_key = addition_key.chop
      entry[base_key] = y[base_key] + entry.delete(addition_key)
    end
  end

  custom_matrix.each do |matrix_entry|
    expand_additions.call matrix_entry

    ruby_versions.each do |ruby_version|
      primary_inclusions << { "rvm" => ruby_version }.merge(matrix_entry)
    end
  end

  y["matrix"]["include"][0, 0] = primary_inclusions

  y["matrix"]["include"].each do |entry|
    expand_additions.call entry
  end

  File.open(".travis.yml", "w") do |f|
    f.write "# This file is autogenerated from `.travis.source.yml` by `rake travis`\n"
    YAML.dump(y, f)
  end
end
