source 'http://rubygems.org'

<%= rails_gemfile_entry -%>

<%= database_gemfile_entry -%>

# Asset template engines
<%= "gem 'json'\n" if RUBY_VERSION < "1.9.2" -%>
gem 'sass', '~> 3.1.0.alpha'
gem 'coffee-script'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# <%= gem_for_ruby_debugger %>

<%= gem_for_turn -%>