
/*
 *= require_self
 *= require action_cable/consumer
 */

// Generated by CoffeeScript 1.10.0
(function() {
  this.ActionCable = {
    INTERNAL: "{\"identifiers\":{\"ping\":\"_ping\"},\"message_types\":{\"confirmation\":\"confirm_subscription\",\"rejection\":\"reject_subscription\"}}",
    createConsumer: function(url) {
      if (url == null) {
        url = this.getConfig("url");
      }
      return new ActionCable.Consumer(this.createWebSocketURL(url));
    },
    getConfig: function(name) {
      var element;
      element = document.head.querySelector("meta[name='action-cable-" + name + "']");
      return element != null ? element.getAttribute("content") : void 0;
    },
    createWebSocketURL: function(url) {
      var a;
      if (url && !/^wss?:/i.test(url)) {
        a = document.createElement("a");
        a.href = url;
        a.href = a.href;
        a.protocol = a.protocol.replace("http", "ws");
        return a.href;
      } else {
        return url;
      }
    }
  };

}).call(this);
