require 'active_relation/extensions/object'
require 'active_relation/extensions/class'
require 'active_relation/extensions/array'
require 'active_relation/extensions/hash'
require 'active_relation/extensions/range'
require 'active_relation/extensions/nil_class'