# Edit this Gemfile to bundle your application's dependencies.
source :gemcutter

<% if !dev_or_edge? %>
gem "rails", "<%= Rails::VERSION::STRING %>"
<% end -%>

## Bundle edge rails:
<%- if options.dev? -%>
path "<%= Rails::Generators::RAILS_DEV_PATH %>", :glob => "{*/,}*.gemspec"
gem "rails", "<%= Rails::VERSION::STRING %>"
<%- else -%>
<%= "# " unless options.edge? %>gem "rails", :git => "git://github.com/rails/rails.git"
<%- end -%>

<% unless options[:skip_activerecord] -%>
<% if options[:database] == 'sqlite3' -%>
# ActiveRecord requires a database adapter. By default,
# Rails has selected sqlite3.
<% end -%>
gem "<%= gem_for_database %>"
<% end -%>

## Bundle the gems you use:
# gem "bj"
# gem "hpricot", "0.6"
# gem "sqlite3-ruby", :require_as => "sqlite3"
# gem "aws-s3", :require_as => "aws/s3"

## Bundle gems used only in certain environments:
# gem "rspec", :only => :test
# only :test do
#   gem "webrat"
# end
