exclude :test_table_options_with_ROW_FORMAT, <<~MSG
  Failure
  Expected /create_table "mysql_table_options", charset: "utf8mb4"(?:, collation: "\w+")?, options: "ENGINE=InnoDB ROW_FORMAT=REDUNDANT", force: :cascade/ to match "# This file is auto-generated from the current state of the database. Instead\n# of editing this file, please use the migrations feature of Active Record to\n# incrementally modify your database, and then regenerate this schema definition.\n#\n# This file is the source Rails uses to define your schema when running `bin/rails\n# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to\n# be faster and is potentially less error prone than running all of your\n# migrations from scratch. Old migrations may fail to apply correctly if those\n# migrations use external dependencies or application code.\n#\n# It's strongly recommended that you check this file into your version control system.\n\nActiveRecord::Schema[7.1].define(version: 0) do\n  create_table \"mysql_table_options\", charset: \"utf8mb4\", collation: \"utf8mb4_bin\", force: :cascade do |t|\n  end\n\nend\n".
MSG
exclude :test_charset_and_partitioned_table_options, <<~MSG
  Failure
  Expected /create_table "mysql_table_options", primary_key: \["id", "account_id"\], charset: "utf8mb4", collation: "utf8mb4_bin", options: "ENGINE=InnoDB\\n(\/\*!50100)? PARTITION BY HASH \(`account_id`\)\\nPARTITIONS 128( \*\/)?", force: :cascade/ to match "# This file is auto-generated from the current state of the database. Instead\n# of editing this file, please use the migrations feature of Active Record to\n# incrementally modify your database, and then regenerate this schema definition.\n#\n# This file is the source Rails uses to define your schema when running `bin/rails\n# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to\n# be faster and is potentially less error prone than running all of your\n# migrations from scratch. Old migrations may fail to apply correctly if those\n# migrations use external dependencies or application code.\n#\n# It's strongly recommended that you check this file into your version control system.\n\nActiveRecord::Schema[7.1].define(version: 0) do\n  create_table \"mysql_table_options\", primary_key: [\"id\", \"account_id\"], charset: \"utf8mb4\", collation: \"utf8mb4_bin\", options: \"ENGINE=InnoDB\\nPARTITION BY HASH (`account_id`) PARTITIONS 128\", force: :cascade do |t|\n    t.bigint \"id\", null: false, auto_increment: true\n    t.bigint \"account_id\", null: false, unsigned: true\n  end\n\nend\n".
MSG
exclude :test_table_options_with_ENGINE, <<~MSG
  Failure
  Expected /create_table "mysql_table_options", charset: "utf8mb4"(?:, collation: "\w+")?, options: "ENGINE=MyISAM", force: :cascade/ to match "# This file is auto-generated from the current state of the database. Instead\n# of editing this file, please use the migrations feature of Active Record to\n# incrementally modify your database, and then regenerate this schema definition.\n#\n# This file is the source Rails uses to define your schema when running `bin/rails\n# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to\n# be faster and is potentially less error prone than running all of your\n# migrations from scratch. Old migrations may fail to apply correctly if those\n# migrations use external dependencies or application code.\n#\n# It's strongly recommended that you check this file into your version control system.\n\nActiveRecord::Schema[7.1].define(version: 0) do\n  create_table \"mysql_table_options\", charset: \"utf8mb4\", collation: \"utf8mb4_bin\", force: :cascade do |t|\n  end\n\nend\n".
MSG
exclude :test_table_options_with_CHARSET, <<~MSG
  Failure
  Expected /create_table "mysql_table_options", charset: "latin1", force: :cascade/ to match "# This file is auto-generated from the current state of the database. Instead\n# of editing this file, please use the migrations feature of Active Record to\n# incrementally modify your database, and then regenerate this schema definition.\n#\n# This file is the source Rails uses to define your schema when running `bin/rails\n# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to\n# be faster and is potentially less error prone than running all of your\n# migrations from scratch. Old migrations may fail to apply correctly if those\n# migrations use external dependencies or application code.\n#\n# It's strongly recommended that you check this file into your version control system.\n\nActiveRecord::Schema[7.1].define(version: 0) do\n  create_table \"mysql_table_options\", charset: \"latin1\", collation: \"latin1_bin\", force: :cascade do |t|\n  end\n\nend\n".
MSG
