#!/bin/sh

set -e

dir="$1"
cmd="$2"

if [ -n "$PRE_STEPS" ]; then
  echo
  echo "--- pre steps"
  eval "$PRE_STEPS"
  echo "+++ "
fi

echo
echo "--- bundle env"
bundle env
echo "+++  "

if ! [ -d "$PWD/railties/exe" ]; then
  export PATH="$PATH:$PWD/railties/bin"
fi

echo "+++ $dir: $cmd"

cd "$dir"
exec bundle exec /bin/sh -e -c "$cmd"
