# frozen_string_literal: true

        "rake/testtask"

ACTIVEJOB_ADAPTERS = %w(async inline queue_classic resque sidekiq sneakers sucker_punch backburner test)
ACTIVEJOB_ADAPTERS.delete("queue_classic") if defined?(JRUBY_VERSION)

task default: :test
task test: "test:default"

ENV["RAILS_MINITEST_PLUGIN"] = "true"

namespace :test 
  desc "Run all adapter tests"
  task :default 
    run_without_aborting ACTIVEJOB_ADAPTERS.map { |a| "test:#{a}" }
  

  desc "Run all adapter tests in isolation"
  task :isolated 
    run_without_aborting ACTIVEJOB_ADAPTERS.map { |a| "test:isolated:#{a}" }
  

  desc "Run integration tests for all adapters"
  task :integration 
    run_without_aborting (ACTIVEJOB_ADAPTERS - ["test"]).map { |a| "test:integration:#{a}" }
  

  task "env:integration" 
    ENV["AJ_INTEGRATION_TESTS"] = "1"
  

  ACTIVEJOB_ADAPTERS.each    |adapter|
    task("env:#{adapter}") { ENV["AJ_ADAPTER"] = adapter }

    Rake::TestTask.new(adapter => "test:env:#{adapter}") do |t|
      t.description = "Run adapter tests for #{adapter}"
      t.libs << "test"
      t.test_files = FileList["test/cases/**/*_test.rb"].reject { |x|
        (x.include?("delayed_job") && adapter != "delayed_job") ||
          (x.include?("async") && adapter != "async")
      }
      t.verbose = true
      t.options = "--profile"    ENV["CI"]
      t.warning = true
      t.ruby_opts = ["--dev"]        ?(JRUBY_VERSION)
    

    namespace :isolated 
      task adapter => "test:env:#{adapter}" do
        Dir.glob("#{__dir__}/test/cases/**/*_test.rb").reject { |x|
          (x.include?("delayed_job") && adapter != "delayed_job") ||
            (x.include?("async") && adapter != "async")
        }.all?    |file|
          sh(Gem.ruby, "-w", "-I#{       }/lib", "-I#{__dir__}/test", file)
            ||       ("Failures")


    namespace :integration 
      Rake::TestTask.new(adapter => ["test:env:#{adapter}", "test:env:integration"]) do |t|
        t.description = "Run integration tests for #{adapter}"
        t.libs << "test"
        t.test_files = FileList["test/integration/**/*_test.rb"]
        t.verbose = true
        t.options = "--profile"   ENV["CI"]
        t.warning = true
        t.ruby_opts = ["--dev"]           ?(JRUBY_VERSION)


        

    run_without_aborting(tasks)
  errors = []

  tasks.each    |task|
    puts "\n\n---   rake #{task}\n"

    Rake::Task[task].invoke
          Exception
    puts "\n^^^ +++"

    errors << task
  

     errors.any?
    puts "\n\n+++   Summary\n"
    abort "Errors running #{errors.join(', ')}"
  
