rails_root = Pathname.new(File.dirname(__FILE__)).join("..")

Gem.sources.each { |uri| source uri }

gem "rack", "1.0.1", :git => "git://github.com/rails/rack.git", :branch => "rack-1.0"
gem "rack-test", "~> 0.5.0"
gem "activesupport", "3.0.pre", :vendored_at => rails_root.join("activesupport")
gem "activemodel", "3.0.pre", :vendored_at => rails_root.join("activemodel")
gem "activerecord", "3.0.pre", :vendored_at => rails_root.join("activerecord")
gem "erubis", "~> 2.6.0"

only :test do
  gem "mocha"
  gem "sqlite3-ruby"
  gem "RedCloth"
end

disable_system_gems
