rails_root = Pathname.new(File.dirname(__FILE__)).join("..")

gem "rack", "~> 1.0.0"
gem "rack-test", "~> 0.4.2"
gem "activesupport", "3.0.pre", :vendored_at => rails_root.join("activesupport")
gem "activemodel", "3.0.pre", :vendored_at => rails_root.join("activemodel")

only :test do
  gem "mocha"
  gem "sqlite3-ruby"
  gem "RedCloth"
end

disable_system_gems
