# frozen_string_literal: true

require "base64"
require "rake/testtask"
require "pathname"
require "open3"
require "action_cable"

task default: :test

ENV["RAILS_MINITEST_PLUGIN"] = "true"

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList["#{__dir__}/test/**/*_test.rb"]
  t.warning = true
  t.verbose = true
  t.options = "--profile" if ENV["CI"]
  t.ruby_opts = ["--dev"] if defined?(JRUBY_VERSION)
end

namespace :test do
  task isolated: :railties do
    Dir.glob("test/**/*_test.rb").all? do |file|
      sh(Gem.ruby, "-w", "-Ilib:test", file)
    end || raise("Failures")
  end

  task :integration do
    system(Hash[*Base64.decode64(ENV.fetch("ENCODED", "")).split(/[ =]/)], "yarn", "test")
    exit($?.exitstatus) unless $?.success?
  end

  task :railties do
    ["action_cable/engine"].all? do |railtie|
      sh(Gem.ruby, "-r", railtie, "-e", "'OK'")
    end || raise("Failures")
  end
end

namespace :assets do
  desc "Generate ActionCable::INTERNAL JS module"
  task :codegen do
    require "json"
    require "action_cable"

    File.open(File.join(__dir__, "app/javascript/action_cable/internal.js").to_s, "w+") do |file|
      file.write("export default #{JSON.pretty_generate(ActionCable::INTERNAL)}\n")
    end
  end
end
