require File.dirname(__FILE__) + '/module/inclusion'
require File.dirname(__FILE__) + '/module/attribute_accessors'
require File.dirname(__FILE__) + '/module/attr_internal'
require File.dirname(__FILE__) + '/module/attr_accessor_with_default'
require File.dirname(__FILE__) + '/module/delegation'
require File.dirname(__FILE__) + '/module/introspection'
require File.dirname(__FILE__) + '/module/loading'
require File.dirname(__FILE__) + '/module/aliasing'
