inherit_from:
  - '../.rubocop.yml'

Layout/IndentationConsistency:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Performance/UnfreezeString:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false
