#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "open3"

VARS = {
  "localWorkspaceFolderBasename" => Dir.pwd.split(File::SEPARATOR).last
}

data = File.binread ".devcontainer/devcontainer.json"
data.gsub!(/^\s*\/\/.*$/, "") # strip comments
info = JSON.load data

working_dir = info["workspaceFolder"].gsub(/\${([^}]*)}/) { |x|
  VARS.fetch($1)
}

env = info["containerEnv"].map { |k, v| "-e #{k}=#{v}" }.join " "

case ARGV[0]
when "up"
  system "docker", "compose", "-f", ".devcontainer/#{info["dockerComposeFile"]}", "up"
when "run-user-commands"
  service_id, _, _ = Open3.capture3("docker ps -q -f name=#{info["service"]}")
  system "docker exec #{env} -w #{working_dir} -it #{service_id.chomp} /bin/bash -i #{info["postCreateCommand"]}"
when "sh"
  service_id, _, _ = Open3.capture3("docker ps -q -f name=#{info["service"]}")
  system "docker exec #{env} -w #{working_dir} -it #{service_id.chomp} /bin/bash"
end
