#!/usr/bin/env ruby
# Example:
#   tools/profile activesupport/lib/active_support.rb
ENV['NO_RELOAD'] ||= '1'
ENV['RAILS_ENV'] ||= 'development'

# TODO: replace with functionality from code_metrics gem
