# frozen_string_literal: true

module RailsGuides
  class SearchIndexDocument
    NUMBER_RE = /^\d+\.?\d*$/
    MIN_WORD_LENGTH = 4

    attr_accessor :id

    def initialize(guide, anchor, title, heading, subheading)
      @id = "#{guide}#{anchor}"
      @title = title
      @heading = heading
      @subheading = subheading
      @lines = []
    end

    def append_line(line)
      filtered = (line.downcase.split - stop_words)
                    .map { |word| word.strip }
                    .reject { |word| word.length < MIN_WORD_LENGTH }
                    .reject { |word| word =~ NUMBER_RE }
                    .join(" ")
      @lines << filtered
    end

    def to_json(*args)
      {
        id: @id,
        title: @title,
        heading: @heading,
        subheading: @subheading,
        content:  @lines.join(" ")
      }.to_json(*args)
    end

    private
      def stop_words
        # This list can be generated by running the following command on a unix system
        # tr -c '[:alnum:]' '[\n*]' < source/active_record_querying.md | sort | uniq -c | sort -nr | head  -20
        %w( a an and are as at be by can for from has he in is it its of on or that the this to was were will with you your )
      end
  end
end
