Gem.sources.each { |uri| source uri }
sibling = "#{File.dirname(__FILE__)}/.."

gem "mocha"

gem "arel", :git => "git://github.com/rails/arel.git"
gem "rack", "1.0.1", :git => "git://github.com/rails/rack.git", :branch => "rack-1.0"
gem "rack-test", "~> 0.5.0"

%w(activesupport activemodel actionpack actionmailer activerecord activeresource).each do |lib|
  gem lib, '3.0.pre', :vendored_at => "#{sibling}/#{lib}"
end
