name: Rail Inspector

on:
  pull_request:
    paths:
    - "tools/rail_inspector/**"
  push:
    paths:
    - "tools/rail_inspector/**"

permissions:
  contents: read

jobs:
  rail_inspector:
    name: rail_inspector tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Remove Gemfile.lock
        run: rm -f Gemfile.lock
      - name: Set up Ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - run: cd tools/rail_inspector && bundle exec rake
