name: Release

on:
  release:
    types: [published]

jobs:
  release:
    permissions:
      contents: write
      id-token: write

    environment: release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - name: Set up Ruby
      uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1
      with:
        ruby-version: ruby
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: lts/*
        registry-url: 'https://registry.npmjs.org'
    - name: Configure trusted publishing credentials
      uses: rubygems/configure-rubygems-credentials@bc6dd217f8a4f919d6835fcfefd470ef821f5c44 # v1.0.0
    # Ensure npm 11.5.1 or later is installed
    - name: Update npm
      run: npm install -g npm@latest
    - name: Bundle install
      run: bundle install
      working-directory: tools/releaser
    - name: Run release rake task
      run: bundle exec rake push
      shell: bash
      working-directory: tools/releaser
    - name: Wait for release to propagate
      run: gem exec rubygems-await pkg/*.gem
      shell: bash
