source "http://rubygems.org"

gem "rails", :git => "http://github.com/rails/rails.git"
gem "arel" , :git => "http://github.com/rails/arel.git"
gem "rack" , :git => "http://github.com/rack/rack.git"
gem "capybara", ">= 0.3.9"
gem "sqlite3-ruby", :require => "sqlite3"

if RUBY_VERSION < '1.9'
  gem "ruby-debug", ">= 0.10.3"
end
