#!/usr/bin/env rake
begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

require 'rake/rdoctask'

Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = '<%= camelized %>'
  rdoc.options << '--line-numbers' << '--inline-source'
  rdoc.rdoc_files.include('README.rdoc')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

<% if full? && !options[:skip_active_record] -%>
namespace :app do
  load File.expand_path("../<%= dummy_path -%>/Rakefile", __FILE__)

  task :"db:load_config" do
    ActiveRecord::Migrator.migrations_paths = Rails.application.config.paths["db/migrate"].to_a +
                                              <%= camelized %>::Engine.config.paths["db/migrate"].to_a
  end
end
<% end -%>

